services:
  e2e-tests:
    build: .
    image: bootcamp/ext-e2e:latest
    environment:
      - CI=true
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: npm run test:e2e
    shm_size: 2gb 