name: CI - Build e Testes da Extensão

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do repositório
        uses: actions/checkout@v4

      - name: 2. Configurar ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 3. Instalar dependências do projeto
        run: npm ci

      - name: 4. Instalar navegadores do Playwright
        run: npx playwright install --with-deps chromium

      - name: 5. Construir a extensão
        run: npm run build

      - name: 6. Executar testes End-to-End com Playwright
        run: npm run test:e2e

      - name: 7. Publicar relatório de testes (em caso de falha ou sucesso)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: 8. Publicar pacote da extensão (.zip)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: dist/extension.zip
          retention-days: 30